---
# filename: roles/nginx/tasks/configure.yml
- name: create php virtual hosts
  template:
    src: php_vhost.j2
    dest: /etc/nginx/conf.d/{{ item.key }}.conf
  with_dict: "{{ nginx['phpsites'] }}"
  notify:
      - restart nginx service
