---
mysql:
  config:
    bind: 127.0.0.1
    pid: /var/run/mysqld/mysqld.pid
    socket: /var/run/mysqld/mysqld.sock
    cnfpath: /etc/mysql/my.cnf
  service: mysql
  pkg:
    client: mysql-client
    python: python-mysqldb

